dist: trusty
sudo: required

language: c

compiler:
 - clang
 - gcc

before_script:
 - sudo apt-get install libldap2-dev libmysqlclient-dev libpq-dev libssl-dev
 - ./.travis-libsodium.sh
 - ./autogen.sh

script:
 - ./configure --disable-dependency-tracking --with-everything --with-ldap --with-mysql --with-pgsql --with-tls
 - make -j$(nproc) distcheck
 - make distclean
 - ./configure --disable-dependency-tracking --with-everything --with-ldap --with-mysql --with-pgsql --with-tls --without-privsep
 - make -j$(nproc) distcheck
 - make distclean
 - ./configure --disable-dependency-tracking --with-tls
 - make -j$(nproc) distcheck
 - make distclean
 - ./configure --disable-dependency-tracking --with-minimal
 - make -j$(nproc) distcheck
 - make distclean
 - ./configure --disable-dependency-tracking --with-minimal --without-privsep
 - make -j$(nproc) distcheck
 - make distclean
